### ISSUE TITLE
Incompatability With Django 1.8

### ISSUE THREAD

**Issue by sethdenner** [django-nonrel/djangotoolbox#61]
djangotoolbox doesn't work on django 1.8.

After the work that was done by @kavdev in #56  it seems like most of the errors are generated from Django moving around their db modules and packages significantly in this release. 

Can we get #56 merged in so we can work on porting to Django 1.8?

**Comment by kavdev** [comment]
Sorry it took so long for me to get around to this, but #64. Please give it a shot and let me know if I missed anything.

**Comment by FeroxTL** [comment]
There are some imports, that does not work in 1.8, what must be:

    #base.py
    from django.conf import settings
    from django.db.backends.base.features import BaseDatabaseFeatures
    from django.db.backends.base.operations import BaseDatabaseOperations
    from django.db.backends.base.base import BaseDatabaseWrapper
    from django.db.backends.base.client import BaseDatabaseClient
    from django.db.backends.base.validation import BaseDatabaseValidation
    from django.db.backends.base.introspection import BaseDatabaseIntrospection

    #creation.py
    from django.db.backends.base.creation import BaseDatabaseCreation

**Comment by kavdev** [comment]
Not sure why you're getting an error, but those imports are indeed correct. See [here](https://docs.djangoproject.com/en/1.8/releases/1.8/#database-backend-api)

**Comment by kavdev** [comment]
I've committed more changes since you've looked at it though; there might have been a bug that should now be resolved.

**Comment by FeroxTL** [comment]
In master branch are another imports https://github.com/django-nonrel/djangotoolbox/blob/master/djangotoolbox/db/base.py#L5

In django 1.7.x it worked, because all imports were in init file https://github.com/django/django/blob/stable/1.6.x/django/db/backends/__init__.py
But in 1.8 this file is empty, so all imported classes are in another location https://github.com/django/django/blob/stable/1.8.x/django/db/backends/__init__.py

In my last comment I wrote how it must be imported

**Comment by kavdev** [comment]
The pull request I mentioned (#64) was created to fix all off the issues you've mentioned. If you want to test the new changes, you need to checkout [the incoming changeset](https://github.com/kavdev/djangotoolbox/).

**Comment by aburgel** [comment]
Fixed in #64
